### PR TITLE
Tracker: meblem4.pl savecart.pl

### PR DESCRIPTION
**Pull request by trackerless**
They are using this code on their own site and e.g. meblem4.pl

### CODE REVIEW

**Comment by trackerless** [comment]
fyi @ryanbr

**Comment by smed79** [comment]
https://github.com/easylist/easylist/pull/2061

**Comment by krystian3w** [comment]
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...

**Comment by peace2000** [comment]
@trackerless @ryanbr This can be closed as it's implemented.

**Pull request closed without merging**
